[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 3    

[[main]]
  identifier = "posts"
  name = "文章"
  url = "posts"
  weight = 1
    
[[main]]
  identifier = "notes"
  name = "笔记"
  url = "notes"
  weight = 2

[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 4

