baseURL = "https://bytebody.github.io/"
languageCode = "zh-cn"
title = "Byte Body"
theme = "paper"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles/"
    weight = 20

  [[menu.main]]
    identifier = "notes"
    name = "Notes"
    url = "/notes/"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40
