baseURL = "https://bytebody.github.io/"
title = "Byte Body"
theme = "paper"
languageCode = "zh-Hans"

[menu]
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

[[params.social]]
  name = "email"
  url  = "mailto:bytebody@gmail.com"

[[params.social]]
  name = "github"
  url  = "https://github.com/bytebody"

